name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps for multi-arch
      run: |
       sudo apt-get update -q -y
       sudo apt-get -qq install -y qemu qemu-user-static
       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        
    - name: Run the build process with Docker
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/7dog123/7dog123/ee-docker:latest
        run: rm -rf ps2toolchain-*

    - name: Build the Docker image
      run: |
       docker run --rm --privileged ghcr.io/7dog123/7dog123/ee-docker:latest
       docker image save ghcr.io/7dog123/7dog123/ee-docker:latest > ee-armhf.tar

    - name: Release
      if: startsWith(github.ref, 'refs/heads/master')
      uses: softprops/action-gh-release@v1
      with:
        files: ee-armhf.tar
        prerelease: false
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- uses: actions/upload-artifact@v2
     # with:
      #  name: ee-armhf
      #  path: ee-armhf.tar
