name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  docker-pull:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: install deps for multi-arch
      run: |
       sudo apt-get update -q -y
       sudo apt-get -qq install -y qemu qemu-user-static
       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
         
    - name: Build the Docker image
      run: docker pull ghcr.io/7dog123/7dog123/mipsel-armhf:latest

    build-container:
      runs-on: [build]
      container:
         image: ghcr.io/7dog123/7dog123/mipsel-armhf:latest
